### ISSUE TITLE
改名検討

### ISSUE THREAD

**Issue by 54m** [go-generalize/firestore-repo#108]
v2に上げるときに改名したい
↓ コメントで案募集

**Comment by huequica** [comment]
- campfire
    - ドキュメントの構造組む感じがそれっぽい
    - 某サービスと命名が被るのでなんかいい感じに捻らないとよくなさそう
- firestarter
    - Firestoreの運用に困らず一意の扱い方を提供する意がこれに似ているのかなと
- flint
    - 火打ち石の意
    - 積み上げられた薪(設計)に火(実装)をもたらす、的な意味合いはつけれるかな

**Comment by tsuzu** [comment]
Firestoreに力を与えるということで燃料計とか(Fuel, Gas, Gasolineなど)

**Comment by huequica** [comment]
- chackaman
  - flint が linter を想起させる(`ehu rint` の読み)ので考えものだなあ、という懸念事項に対しての代替案

**Comment by huequica** [comment]
Fuel, なんか炎上を想起させる…(仕事に毒されすぎ)

**Comment by 54m** [comment]
fuelいいと思うんだけどなー

**Comment by tsuzu** [comment]
チャッカマン、商標っぽいので怒られ発生しないかな・・・

似た感じでmatch/matchboxなどもありますね

**Comment by huequica** [comment]
あ〜〜商標登録されてるのか、それは確かにまずそう

**Comment by tsuzu** [comment]
火花という意味でspark, flash, sparkle, glow, ember, brandなどがあるらしい
sparkはどうみてもApache Sparkだしflashは多義すぎる

**Comment by aerith** [comment]
火山 + go で volcago

**Comment by huequica** [comment]
- pyra
  - (これ何？とは言わないでおく(ネタの域を出ない(ｸﾞｸﾞﾗﾋﾞﾘﾃｨはおそらく最悪)))

**Comment by huequica** [comment]
- blueFire
  - なんか炎自体を指してもいいかも、と思った
  - red だと Ruby っぽいので blue にした
    - 火力も高くちょうど gopher と色もマッチしている

**Comment by ryo88c** [comment]
agnicast（agni-cast）
agni: サンスクリット語で火の神
cast: 鋳造

**Comment by 54m** [comment]
valcagoに決定！
別issueにてリポジトリを変えるか、リポジトリ名を変えるかどうかの議論
